<?php

// This is an example of a script that can be used to receive the config generated by
// NConf, and then deployed by HTTP(s)-POST to a remote server.

$targetdir = "/your/path/here";

if(is_uploaded_file($_FILES["file"]["tmp_name"])) {

    if(copy($_FILES["file"]["tmp_name"], $targetdir."/".$_FILES["file"]["name"])) {
        echo "OK";
    }else{
        echo "upload to remote server failed";
        echo "<br>".$targetdir."/".$_FILES["file"]["name"];
    }

}else{
    echo "trying to send invalid file";
}

?>
